// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAztdySLjPIwjWXxA-tSPftJTfaM8VsYfI',
    appId: '1:718694861203:android:108bc4a858390750dd0066',
    messagingSenderId: '718694861203',
    projectId: 'qoraa-f50e1',
    storageBucket: 'qoraa-f50e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxpWu5TGtoawpTaEWqC2VTiPrLbkie6Js',
    appId: '1:718694861203:ios:1f5724d65d51da77dd0066',
    messagingSenderId: '718694861203',
    projectId: 'qoraa-f50e1',
    storageBucket: 'qoraa-f50e1.appspot.com',
    androidClientId: '718694861203-895a4v9ba3i9ccph78rn36gr7m1hsvun.apps.googleusercontent.com',
    iosClientId: '718694861203-s1vugqm6v4ivrql5a2rabldv9h8ptt57.apps.googleusercontent.com',
    iosBundleId: 'com.webiots.probotgpt',
  );
}
